#!/usr/bin/env bash
# One deploy: fast-forward main, build both surfaces, restart both, verify.
#
# Build and restart are deliberately one step. build.sh writes into
# .next-public and .next-demo while the old servers are still reading them, so
# every minute between building and restarting is a minute those servers can
# fail on a chunk that no longer matches the manifest. Leaving the restart to a
# human is also how both surfaces spent a day serving a build from Monday.
#
# Exit codes: 0 deployed (or already current), 1 refused or failed.
set -euo pipefail

cd "$(dirname "$0")/../.."
UID_NUM="$(id -u)"

# Two deploys at once would have both builds writing the same .next-public and
# .next-demo, which produces a bundle that matches no manifest. launchd will not
# run two copies of the autodeploy job, but a hand-run deploy can still land on
# top of a scheduled one. mkdir is the atomic test-and-set available here.
LOCK_DIR=".deploy.lock"
if ! mkdir "$LOCK_DIR" 2>/dev/null; then
  # A killed deploy leaves the directory behind. Reclaim it only when the
  # recorded process is genuinely gone, so a live deploy still blocks.
  stale_pid="$(cat "$LOCK_DIR/pid" 2>/dev/null || true)"
  if [ -n "$stale_pid" ] && kill -0 "$stale_pid" 2>/dev/null; then
    echo "refusing to deploy: another deploy is running (pid $stale_pid)" >&2
    exit 1
  fi
  echo "==> Clearing stale deploy lock (pid ${stale_pid:-unknown} is gone)"
  rm -rf "$LOCK_DIR"
  mkdir "$LOCK_DIR" || { echo "could not acquire the deploy lock" >&2; exit 1; }
fi
echo "$$" >"$LOCK_DIR/pid"
trap 'rm -rf "$LOCK_DIR"' EXIT

# next-env.d.ts is regenerated by every build and flips between dist dirs
# depending on whether `next dev` or this script ran last, so it is always dirty
# and would block the fast-forward. It is generated, not authored.
git checkout -- next-env.d.ts 2>/dev/null || true

branch="$(git rev-parse --abbrev-ref HEAD)"
if [ "$branch" != "main" ]; then
  echo "refusing to deploy: on '$branch', not main" >&2
  exit 1
fi

# Fail closed on uncommitted work. This checkout is also a development tree, so
# a deploy must never quietly ship something that is not on origin/main, and
# must never destroy work in progress to get there.
if ! git diff --quiet HEAD --; then
  echo "refusing to deploy: uncommitted changes in the working tree" >&2
  git status --short >&2
  exit 1
fi

git fetch --quiet origin main
before="$(git rev-parse HEAD)"
git merge --ff-only origin/main
after="$(git rev-parse HEAD)"

if [ "$before" = "$after" ]; then
  echo "==> Checkout already at ${after:0:7}"
else
  echo "==> ${before:0:7} -> ${after:0:7}"
fi

DEPLOY_WILL_RESTART=1 ./scripts/deploy/build.sh

echo "==> Restarting all surfaces"
launchctl kickstart -k "gui/$UID_NUM/local.zencub-rag-public"
launchctl kickstart -k "gui/$UID_NUM/local.zencub-rag-instructors"
launchctl kickstart -k "gui/$UID_NUM/local.zencub-rag-demo"

# Verify against the stamp rather than a 200, so a server that came back up on
# the previous bundle still counts as a failed deploy.
expected="$(git rev-parse --short HEAD)"
echo "==> Waiting for the public surface to report $expected"
for _ in $(seq 1 30); do
  live="$(curl -fsS --max-time 5 http://127.0.0.1:3418/api/health 2>/dev/null \
    | sed -n 's/.*"sha":"\([^"]*\)".*/\1/p')" || live=""
  if [ "$live" = "$expected" ]; then
    echo "==> public 3418 live on $live"

    # The instructors surface exposes /api/health too, so it is checked against
    # the same stamp rather than a bare 200.
    instructors="$(curl -fsS --max-time 5 http://127.0.0.1:3420/api/health 2>/dev/null \
      | sed -n 's/.*"sha":"\([^"]*\)".*/\1/p')" || instructors=""
    if [ "$instructors" != "$expected" ]; then
      echo "deployed, but instructors 3420 reports '${instructors:-unreachable}', not $expected" >&2
      exit 1
    fi
    echo "==> instructors 3420 live on $instructors"

    # The demo answers 401 on /api/health by design (the PIN gate fails closed),
    # so its liveness check is the unlock page instead.
    if curl -fsS -o /dev/null --max-time 5 http://127.0.0.1:3419/unlock; then
      echo "==> demo 3419 serving /unlock"
      exit 0
    fi
    echo "deployed, but demo 3419 is not serving /unlock" >&2
    exit 1
  fi
  sleep 2
done

echo "deploy finished but 3418 never reported $expected (last saw '${live:-unreachable}')" >&2
exit 1
