#!/usr/bin/env bash
# One deploy: fast-forward main, build every surface, restart them all, verify
# every one of them.
#
# Build and restart are deliberately one step. build.sh writes into
# .next-public and .next-demo while the old servers are still reading them, so
# every minute between building and restarting is a minute those servers can
# fail on a chunk that no longer matches the manifest. Leaving the restart to a
# human is also how both surfaces spent a day serving a build from Monday.
#
# Exit codes: 0 deployed (or already current), 1 refused or failed.
set -euo pipefail

cd "$(dirname "$0")/../.."
UID_NUM="$(id -u)"

# Two deploys at once would have both builds writing the same .next-public and
# .next-demo, which produces a bundle that matches no manifest. launchd will not
# run two copies of the autodeploy job, but a hand-run deploy can still land on
# top of a scheduled one. mkdir is the atomic test-and-set available here.
LOCK_DIR=".deploy.lock"
if ! mkdir "$LOCK_DIR" 2>/dev/null; then
  # A killed deploy leaves the directory behind. Reclaim it only when the
  # recorded process is genuinely gone, so a live deploy still blocks.
  stale_pid="$(cat "$LOCK_DIR/pid" 2>/dev/null || true)"
  if [ -n "$stale_pid" ] && kill -0 "$stale_pid" 2>/dev/null; then
    echo "refusing to deploy: another deploy is running (pid $stale_pid)" >&2
    exit 1
  fi
  echo "==> Clearing stale deploy lock (pid ${stale_pid:-unknown} is gone)"
  rm -rf "$LOCK_DIR"
  mkdir "$LOCK_DIR" || { echo "could not acquire the deploy lock" >&2; exit 1; }
fi
echo "$$" >"$LOCK_DIR/pid"
trap 'rm -rf "$LOCK_DIR"' EXIT

# next-env.d.ts is regenerated by every build and flips between dist dirs
# depending on whether `next dev` or this script ran last, so it is always dirty
# and would block the fast-forward. It is generated, not authored.
git checkout -- next-env.d.ts 2>/dev/null || true

branch="$(git rev-parse --abbrev-ref HEAD)"
if [ "$branch" != "main" ]; then
  echo "refusing to deploy: on '$branch', not main" >&2
  exit 1
fi

# Fail closed on uncommitted work. This checkout is also a development tree, so
# a deploy must never quietly ship something that is not on origin/main, and
# must never destroy work in progress to get there.
if ! git diff --quiet HEAD --; then
  echo "refusing to deploy: uncommitted changes in the working tree" >&2
  git status --short >&2
  exit 1
fi

git fetch --quiet origin main
before="$(git rev-parse HEAD)"
git merge --ff-only origin/main
after="$(git rev-parse HEAD)"

if [ "$before" = "$after" ]; then
  echo "==> Checkout already at ${after:0:7}"
else
  echo "==> ${before:0:7} -> ${after:0:7}"
fi

# Decide the target commit ONCE, here, and hand it to the build.
#
# This used to be read twice -- build.sh took its own `git rev-parse --short
# HEAD`, and the verify loop below took another one after the build finished.
# That is a race, and it fired on 2026-08-29: a commit landed in this checkout
# while a build was running, so deploy.sh built 81bb252, then waited for the
# servers to report 0ff5693, then failed and paged. Nothing was broken except
# the question it asked.
#
# This checkout is a development tree as well as the deploy source, so HEAD
# genuinely can move mid-build. The lock above stops two deploys colliding; it
# cannot stop a person committing. So the fix is to stop asking twice: build.sh
# honours an inherited BUILD_SHA, and the verify loop uses the same variable.
# Whatever HEAD does afterwards, a deploy now verifies exactly what it stamped.
expected="$(git rev-parse --short "$after")"
export BUILD_SHA="$expected"

DEPLOY_WILL_RESTART=1 ./scripts/deploy/build.sh

# Restart a surface, tolerating one that is not installed on this machine yet.
#
# This exists because of a near miss: adding the mcp surface to the list below
# while its plist was not yet bootstrapped would have made kickstart return
# non-zero under `set -e`, aborting the deploy *after* build.sh had already
# rewritten the bundles. Every live surface would then have been serving a
# freshly built directory it had never restarted into -- which is the exact
# failure this file's header says it exists to prevent.
#
# A missing job warns loudly and continues. A job that IS installed and fails
# to restart is still a hard failure, because that one is real.
restart_surface() {
  local label="$1"
  if ! launchctl print "gui/$UID_NUM/$label" >/dev/null 2>&1; then
    echo "    WARNING: $label is not installed; skipping its restart."
    echo "             Install it with:"
    echo "             launchctl bootstrap gui/$UID_NUM ~/Library/LaunchAgents/$label.plist"
    return 0
  fi
  launchctl kickstart -k "gui/$UID_NUM/$label"
}

echo "==> Restarting all surfaces"
restart_surface local.zencub-rag-public
restart_surface local.zencub-rag-instructors
restart_surface local.zencub-rag-demo
restart_surface local.zencub-rag-mcp

# Verify against the stamp rather than a 200, so a server that came back up on
# the previous bundle still counts as a failed deploy. `expected` was fixed
# before the build; see the note there.

port_sha() {
  curl -fsS --max-time 5 "http://127.0.0.1:$1/api/health" 2>/dev/null \
    | sed -n 's/.*"sha":"\([^"]*\)".*/\1/p'
}

# All three sha-stamped surfaces restart at the same moment, so checking a
# secondary one exactly once is a race: it fails the deploy for being a few
# seconds slower than 3418 rather than for being broken. Retry briefly, then
# report what it actually last said.
wait_for_sha() {
  local name="$1" port="$2" seen=""
  for _ in $(seq 1 15); do
    seen="$(port_sha "$port")" || seen=""
    if [ "$seen" = "$expected" ]; then
      echo "==> $name $port live on $seen"
      return 0
    fi
    sleep 2
  done
  echo "deployed, but $name $port reports '${seen:-unreachable}', not $expected" >&2
  return 1
}

echo "==> Waiting for the public surface to report $expected"
for _ in $(seq 1 30); do
  live="$(port_sha 3418)" || live=""
  if [ "$live" = "$expected" ]; then
    echo "==> public 3418 live on $live"

    # The instructors surface exposes /api/health too, so it is checked against
    # the same stamp rather than a bare 200.
    wait_for_sha instructors 3420 || exit 1

    # So does the mcp surface. It was restarted here from the day it was added
    # and never verified, so a build that broke only APP_MODE=mcp -- or an mcp
    # process that came back on the previous bundle, or did not come back at
    # all -- was reported as a successful deploy. Found 2026-08-28 by reading
    # this file's own log, which lists public, instructors and demo and stops.
    # It matters more than it looks: 3421 is the only surface with no human
    # watching it, because nobody browses to it.
    wait_for_sha mcp 3421 || exit 1

    # The demo answers 401 on /api/health by design (the PIN gate fails closed),
    # so its liveness check is the unlock page instead.
    if curl -fsS -o /dev/null --max-time 5 http://127.0.0.1:3419/unlock; then
      echo "==> demo 3419 serving /unlock"
      exit 0
    fi
    echo "deployed, but demo 3419 is not serving /unlock" >&2
    exit 1
  fi
  sleep 2
done

echo "deploy finished but 3418 never reported $expected (last saw '${live:-unreachable}')" >&2
exit 1
